(define f
    (let ((a 2) (b 9))
        (lambda (x y)
            (let ((a (+ a x)))
                (lambda (z)
                    (let ((c (+ a y)))
                        (lambda (d)
                            (+ (+ a x) (+ y b) z c d)
                        )
                    )
                )
            )
        )
    )
)
(define g (f 5 3))
(define h (g 4))
(h 6)
